language: php

matrix:
  include:
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "8.0"
    - php: "8.1"

install:
  - composer install

script:
  - php tests/test.php
  - php ./vendor/bin/phpmd src ansi phpmd-ruleset.xml